spring.application.name=ai-panel

#ai
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3.6
spring.ai.ollama.chat.temperature=0.0
spring.ai.ollama.chat.think=true

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/aidb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.open-in-view=false

#minio
minio.endpoint=http://localhost:9000
minio.accessKey=admin_user
minio.secretKey=admin_password123
minio.bucket=files

logging.level.org.springframework.ai.chat.client.advisor.vectorstore=DEBUG
logging.level.org.springframework.ai.tool=DEBUG